package Memos;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table MEMO.
 */
public class Memo {

    private Long id;
    /** Not-null value. */
    private String Name;
    /** Not-null value. */
    private String Address;
    private String Temperature;
    private String Humidity;
    /** Not-null value. */
    private String date;
    private byte[] PictureThumbnail;
    private byte[] Picture;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Memo() {
    }

    public Memo(Long id) {
        this.id = id;
    }

    public Memo(Long id, String Name, String Address, String Temperature, String Humidity, String date, byte[] PictureThumbnail, byte[] Picture) {
        this.id = id;
        this.Name = Name;
        this.Address = Address;
        this.Temperature = Temperature;
        this.Humidity = Humidity;
        this.date = date;
        this.PictureThumbnail = PictureThumbnail;
        this.Picture = Picture;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return Name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String Name) {
        this.Name = Name;
    }

    /** Not-null value. */
    public String getAddress() {
        return Address;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAddress(String Address) {
        this.Address = Address;
    }

    public String getTemperature() {
        return Temperature;
    }

    public void setTemperature(String Temperature) {
        this.Temperature = Temperature;
    }

    public String getHumidity() {
        return Humidity;
    }

    public void setHumidity(String Humidity) {
        this.Humidity = Humidity;
    }

    /** Not-null value. */
    public String getDate() {
        return date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDate(String date) {
        this.date = date;
    }

    public byte[] getPictureThumbnail() {
        return PictureThumbnail;
    }

    public void setPictureThumbnail(byte[] PictureThumbnail) {
        this.PictureThumbnail = PictureThumbnail;
    }

    public byte[] getPicture() {
        return Picture;
    }

    public void setPicture(byte[] Picture) {
        this.Picture = Picture;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
