package com.example.wizart.mytrips.ActiveAndroidDb;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import com.activeandroid.Model;
import com.activeandroid.annotation.Column;
import com.google.android.gms.maps.model.LatLng;

import java.util.ArrayList;
import java.util.Date;


public class Trip extends Model{



    @Column(name = "Distance")
    private long Distance=0;

    @Column(name = "elapsedTime")
    private String elapsedTime=null;

    @Column(name = "AverageSpeed")
    private double AverageSpeed =0;

    @Column(name = "Calories")
    private double Calories =0;

    @Column(name = "arrayRoutePoints")
    private ArrayList<LatLng> arrayRoutePoints = null;

    @Column(name = "steps")
    private long steps=0;

    @Column(name = "startTime",unique = true, onUniqueConflict = Column.ConflictAction.REPLACE)
    private Date startTime=null;

    @Column(name = "endTime")
    private Date endTime=null;

    private ArrayListLAtLngSerializer serPoints;


    @Column(name = "activity")
    private int activity=0;

    @Column(name = "maxSpeed")
    private double maxSpeed=0;




    public void setCalories(double calories) {
        Calories = calories;
    }

    public void setSteps(long steps) {
        this.steps = steps;
    }

    public void setMaxSpeed(double maxSpeed) {
        this.maxSpeed = maxSpeed;
    }

    public long getDistance() {
        return Distance;
    }

    public void setDistance(long distance) {
        Distance = distance;
    }



    public String getElapsedTime() {
        return elapsedTime;
    }

    public void setElapsedTime(String elapsedTime) {
        this.elapsedTime = elapsedTime;
    }

    public double getAverageSpeed() {
        return AverageSpeed;
    }

    public void setAverageSpeed(double averageSpeed) {
        AverageSpeed = averageSpeed;
    }



    public double getCalories() {
        return Calories;
    }

    public void setCalories(int calories) {
        Calories = calories;
    }



    public ArrayList<LatLng> getArrayRoutePoints() {
        return arrayRoutePoints;
    }

    public void setArrayRoutePoints(ArrayList<LatLng> arrayRoutePoints) {
        this.arrayRoutePoints = arrayRoutePoints;
    }

    public long getSteps() {
        return steps;
    }

    public void setSteps(int steps) {
        this.steps = steps;
    }

    public Date getStartTime() {
        return startTime;
    }

    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    public Date getEndTime() {
        return endTime;
    }

    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    public int getActivity() {
        return activity;
    }

    public void setActivity(int activity) {
        this.activity = activity;
    }

    public double getMaxSpeed() {
        return maxSpeed;
    }

    public void setVelocity(double velocity) {
        maxSpeed= velocity;
    }


    public Trip() {
        super();
    }

    public Trip(long distance, String elapsedTime, double averageSpeed, double calories, long steps, Date startTime, Date endTime, double avarageSpeed,double maxSpeed, int activity ) {
        super();
        this.Distance = distance;
        this.elapsedTime = elapsedTime;
        this.AverageSpeed = averageSpeed;
        this.Calories = calories;
        this.steps = steps;
        this.startTime = startTime;
        this.endTime = endTime;
        this.maxSpeed= maxSpeed;
        this.AverageSpeed= avarageSpeed;
        this.activity = activity;
    }

    public ArrayListLAtLngSerializer getSerPoints() {
        return serPoints;
    }

    public void setSerPoints(ArrayListLAtLngSerializer serPoints) {
        this.serPoints = serPoints;
    }
}
